#version 430

struct CS_INPUT{
  float value1;
  float value2;
};

struct CS_OUTPUT{
  float value;
};

layout(set = 0, binding = 0, std140) uniform CB
{
    float offset;
} _23;

layout(set = 0, binding = 1, std430) buffer ComputeBuffer0
{
    CS_INPUT read[];
};

layout(set = 0, binding = 2, std430) buffer ComputeBuffer1
{
    CS_OUTPUT write[];
};

void main()
{
  uvec3 dtid = gl_GlobalInvocationID;
  write[dtid.x].value = read[dtid.x].value1 * read[dtid.x].value2 + _23.offset;
}