#version 430

struct VS_INPUT{
  float value;
};

layout(set = 0, binding = 0, std140) uniform CB
{
    float offset;
} _23;

layout(set = 0, binding = 1, std430) buffer ComputeBuffer0
{
    VS_INPUT read[];
};

layout(set = 0, binding = 2, std430) buffer ComputeBuffer1
{
    VS_INPUT write[];
};

void main()
{
  uvec3 dtid = gl_GlobalInvocationID;
  write[dtid.x].value = read[dtid.x].value * read[dtid.x].value + _23.offset;
}