#version 430
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 3, binding = 1, rgba32f) uniform readonly image2D read1;
layout(set = 3, binding = 0, rgba32f) uniform writeonly image2D write;
layout(set = 1, binding = 2) uniform sampler2D Sampler_read2_sampler;

void _main(uvec3 dtid)
{
    uvec2 index = dtid.xy;
    vec4 storeTemp = imageLoad(read1, ivec2(index)) + textureLod(Sampler_read2_sampler, vec2(0.0), 0.0);
    imageStore(write, ivec2(index), storeTemp);
}

void main()
{
    uvec3 dtid = gl_GlobalInvocationID;
    uvec3 param = dtid;
    _main(param);
}

