struct CS_OUTPUT {
  /* @offset(0) */
  value : f32,
}

alias RTArr = @stride(4) array<CS_OUTPUT>;

struct write {
  /* @offset(0) */
  x_data : RTArr,
}

struct CS_INPUT {
  /* @offset(0) */
  value1 : f32,
  /* @offset(4) */
  value2 : f32,
}

alias RTArr_1 = @stride(8) array<CS_INPUT>;

struct read {
  /* @offset(0) */
  x_data : RTArr_1,
}

struct CB {
  /* @offset(0) */
  offset : f32,
}

@group(0) @binding(1) var<storage, read_write> write_1 : write;

@group(0) @binding(0) var<storage, read> read_1 : read;

@group(0) @binding(0) var<uniform> x_43 : CB;

var<private> dtid_2 : vec3u;

fn x_main_vu3_(dtid : ptr<function, vec3u>) {
  let x_24 = (*(dtid)).x;
  let x_31 = (*(dtid)).x;
  let x_34 = read_1.x_data[x_31].value1;
  let x_36 = (*(dtid)).x;
  let x_39 = read_1.x_data[x_36].value2;
  let x_45 = x_43.offset;
  write_1.x_data[x_24].value = ((x_34 * x_39) + x_45);
  return;
}

fn main_1() {
  var dtid_1 : vec3u;
  var param : vec3u;
  let x_51 = dtid_2;
  dtid_1 = x_51;
  let x_53 = dtid_1;
  param = x_53;
  x_main_vu3_(&(param));
  return;
}

@compute @workgroup_size(1i, 1i, 1i)
fn main(@builtin(global_invocation_id) dtid_2_param : vec3u) {
  dtid_2 = dtid_2_param;
  main_1();
}
