#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct CS_INPUT
{
    float value1;
    float value2;
};

struct CS_OUTPUT
{
    float value;
};

struct CB
{
    float offset;
};

kernel void main0(constant CB& v_23 [[buffer(0)]], device CS_INPUT *read [[buffer(1)]], device CS_OUTPUT *write [[buffer(2)]], uint3 dtid [[thread_position_in_grid]])
{
    write[dtid.x].value = read[dtid.x].value1 * read[dtid.x].value2 + v_23.offset;
}