#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

static inline __attribute__((always_inline))
void _main(thread const uint3& dtid, texture2d<float> read1, texture2d<float> read2, sampler read2_sampler, texture2d<float, access::write> write)
{
    uint2 index = dtid.xy;
    float4 storeTemp = read1.read(uint2(index)) + read2.sample(read2_sampler, float2(0.0), level(0.0));
    write.write(storeTemp, uint2(index));
}

kernel void main0(texture2d<float, access::write> write [[texture(0)]], texture2d<float> read1 [[texture(1)]], texture2d<float> read2 [[texture(2)]], sampler read2_sampler [[sampler(2)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    uint3 dtid = gl_GlobalInvocationID;
    uint3 param = dtid;
    _main(param, read1, read2, read2_sampler, write);
}

